### PR TITLE
IO adjustments + Maven version update

### PR DESCRIPTION
**Pull request by svandenhoek**
- Removed sorting algorithm from command line options (OptionsParser now uses only valid option by default).
- Adjusted the generated output file (includes more information such as PubMed IDs on a per gene-disease combination basis).
- Fix for bash script (non-optional arguments were treated as optional).
- Updated `pom.xml` plugin/dependency versions.
- Updated README.

### CODE REVIEW

**Comment by bartcharbon** [comment]
very minor issue in the repo not related to this PR:
The USAGE of TestNGPreprocessing.sh contains the wrong script name.

readonly USAGE="Usage: **disgenet-data-formatter.sh** [-h] [-d <DIR>]
Description: Runs preparations for unit testing.

**Comment by bartcharbon** [comment]
Code looks fine, functional tests went fine as well. 
However I have a few failing unit tests, in the following test files:
- CommandLineOptionsParserTester
- ModelReadersTester
- QueryStringGeneratorTester

**Comment by svandenhoek** [comment]
> Code looks fine, functional tests went fine as well.
> However I have a few failing unit tests, in the following test files:
> 
>     * CommandLineOptionsParserTester
> 
>     * ModelReadersTester
> 
>     * QueryStringGeneratorTester

I'm not sure how I can reproduce your error. I have tried the following:
- `TestNGPreprocessing.sh` was not run + testing through `testng.xml`: 19 failed, 14 ignored (among 5 classes)
- `TestNGPreprocessing.sh` was run without `-d` + testing through `testng.xml`: 2 failed, 2 ignored (QueryStringGeneratorTester & GenesForPhenotypeRetrieverTester)
- `TestNGPreprocessing.sh` was run with `-d` + testing through `testng.xml`: 0 failed
- `TestNGPreprocessing.sh` was run with `-d` + testing through `test/java/` directory: 1 failed + 3 ignored (only in QueryStringGeneratorTester, caused by NullPointerException due to `afterMethod()` not being treated group-specifically)
- `TestNGPreprocessing.sh` was run with `-d` + testing through `testng.xml` + benchmarking group enabled: 0 failed

So I have 2 questions:
- Was `TestNGPreprocessing.sh` run with the `-d` argument before the tests were done?
- How were the tests done? Through `testng.xml` or differently?

**Comment by svandenhoek** [comment]
> very minor issue in the repo not related to this PR:
> The USAGE of TestNGPreprocessing.sh contains the wrong script name.
> 
> readonly USAGE="Usage: **disgenet-data-formatter.sh** [-h] [-d
> ]
> Description: Runs preparations for unit testing.

Fixed and also made the README more explicit about using `-d` in `TestNGPreprocessing.sh` and regarding the `testng.xml` for testing.

**Pull request merged**
